import openpyxl
import time
from openpyxl import load_workbook
timestr=time.strftime("%Y%m%d-%H%M%S")
add="path to save log file"
file=open(add+"/filename"+timestr+".txt","w")
file.write("start of Process\n")
file.write("=======================================================================\n")
file.write("Reading Data Files\n")
with open("data file as .txt","r") as data:
	lines=data.readlines()
	
file.write("=======================================================================\n")
file.write("Data files read\n")
file.write("=======================================================================\n")
m5F=lines[0].split(",")
m5G=lines[1].split(",")
m5I=lines[2].split(",")
m5J=lines[3].split(",")
m5K=lines[4].split(",")
file.write("Load Template\n")
wb=load_workbook(filename='excel file with formula and iamges and prefilled format/file.xlsx')
file.write("=======================================================================\n")
file.write("Template loaded.Select active worksheet\n")
file.write("=======================================================================\n")
ws=wb.active
file.write("Writing to Excel File\n")
file.write("=======================================================================\n")
ws['F22']=float(m5F[0])
ws['F23']=float(m5F[1])
ws['F28']=float(m5F[2])
ws['F29']=float(m5F[3])
ws['F34']=float(m5F[4])
ws['F35']=float(m5F[5])
ws['F40']=float(m5F[6])
ws['F41']=float(m5F[7])
ws['G22']=float(m5G[0])
ws['G23']=float(m5G[1])
ws['G28']=float(m5G[2])
ws['G29']=float(m5G[3])
ws['G34']=float(m5G[4])
ws['G35']=float(m5G[5])
ws['G40']=float(m5G[6])
ws['G41']=float(m5G[7])
ws['I54']=float(m5I[0])
ws['I55']=float(m5I[1])
ws['I64']=float(m5I[2])
ws['J54']=float(m5J[0])
ws['J55']=float(m5J[1])
ws['J64']=float(m5J[2])
ws['K54']=float(m5K[0])
ws['K55']=float(m5K[1])
ws['K64']=float(m5K[2])
file.write("Data inserted into file\n")
file.write("=======================================================================\n")
file.write("Import image files\n")
file.write("=======================================================================\n")
img=openpyxl.drawing.image.Image("path to image.png")
ws.add_image(img,'C5')
img=openpyxl.drawing.image.Image("path to image.png")
ws.add_image(img,'J5')
img=openpyxl.drawing.image.Image("path to image.png")
ws.add_image(img,'O5')
img=openpyxl.drawing.image.Image("path to image.png")
ws.add_image(img,'Q7')
file.write("Image inserted\n")
wb.save('path to save file...filenmae'+timestr+'.xlsx')
file.write("=======================================================================\n")
file.write("Excel file Created and saved.Log file Created\n")
file.write("+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++\n")
file.write("End of Process")
file.close()

